name: Build and test of Java Project
on: [push]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   uses: actions/checkout@v2
 name: Set up JDK 1.8
 descargarJava: actions/setup-java@v1
 with:
   java-version: 1.8
 compilarMaven: Build with Maven
 run: mvn -B package --file pom.xml
